### ISSUE TITLE
Can you show a demo with metadata

### ISSUE THREAD

**Issue by sudongyuer** [viglucci/rsocket-js-examples#1]
in my project,i set up metadataMimeType text/plain but web site receive null

web site
![image](https://user-images.githubusercontent.com/76603360/145493349-adb52831-3273-45a8-a4d9-1b71cd205632.png)
![image](https://user-images.githubusercontent.com/76603360/145493430-474b6f88-744d-4a88-8e7e-e3fff232db1d.png)

in node server
![image](https://user-images.githubusercontent.com/76603360/145493474-0fed2e11-8538-426d-80f9-c73a1b90f47d.png)

**Comment by sudongyuer** [comment]
your demo  
![image](https://user-images.githubusercontent.com/76603360/145493928-aa94fb89-686f-4bf8-9984-5d02f9dabb5c.png)

**Comment by viglucci** [comment]
I saw your other issue (https://github.com/rsocket/rsocket-js/issues/197), and wasn't able to get metadata to work with `text/plain`. I'm trying to get an example working with composite metadata, but having some issues as well. Going to try and look more into it.

**Comment by viglucci** [comment]
I think there is a bug that causes `metadata` to not be sent to the client.

https://github.com/rsocket/rsocket-js/issues/198
